TARGET = XK-1A
APP_NAME =
XCC_FLAGS = -g -save-temps -Os -report
USED_MODULES = module_i2c module_logging


#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.

XMOS_MAKE_PATH ?= ../..
include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
